# Configuration for support-requests - https://github.com/dessant/support-requests

# Label used to mark issues as support requests
supportLabel: Type: Not a bug

# Comment to post on issues marked as support requests, `{issue-author}` is an
# optional placeholder. Set to `false` to disable
supportComment: >
  Hello @{issue-author}.
  Your reported bug is actually not a bug.
  Please make sure, that you use the [latest version](https://www.spigotmc.org/resources/helpgui.33245/) of HelpGUI.

  If you still have this issue, contact the developer directly on Spigot!

# Close issues marked as support requests
close: true

# Lock issues marked as support requests
lock: false

# Assign `off-topic` as the reason for locking. Set to `false` to disable
setLockReason: false

# Repository to extend settings from
# _extends: repo