#   _   _          _             _____            _   #
#  | | | |        | |           / ____)          (_)  #
#  | |_| |   ___  | |   ____   | /  __   _    _   _   #
#  |_____|  / o \ | |  |  _ \  |_| (__| | |  | | | |  #
#   _   _  |  __/ | |_ | |_) |  ______  | \__/ | | |  #
#  |_| |_|  \___) |__/ |  __/   \____/   \____/  |_|  #
#                      | |                            #
#                      |_|  By Andre_601              #
#                                                     #
# Spigot Resource:                                    #
#   https://www.spigotmc.org/resources/33245/         #
#                                                     #
# GitHub:                                             #
#   https://github.com/Andre601/HelpGUI               #
#                                                     #
# Wiki:                                               #
#   https://github.com/Andre601/HelpGUI/wiki          #

Settings:
  #
  # Debug:        Enable/Disable debug mode. This will print stacktraces and other information prefixed with "[DEBUG]"
  # ShowBanner:   Should the banner be shown in console, when the plugin gets enabled?
  # CheckUpdates: Should HelpGUI check for updates on startup? You can still manually check with /helpgui about
  #
  Debug: false
  ShowBanner: true
  CheckUpdates: true
  DisabledPlayers:
    #
    # Choose which player heads are shown in the GUI.
    #
    # You can define one of three modes available (Listed below).
    #
    # The list (Players:) supports player names and UUIDs.
    # You need to prefix UUIDs with uuid: (Case sensitive)
    #
    # For example:
    # - 'uuid:286f8d0c-b571-4720-b7ab-f2929cb38120' # This is the UUID of the player Andre_601
    #
    # Modes:
    #   blacklist  ->  Players listed below will *NOT* be shown in the GUI (Default Option).
    #   whitelist  ->  Players listed below *WILL ONLY* be shown in the GUI.
    #   staff      ->  Only players with the "helpgui.staff" permission node will be shown in the GUI.
    #
    Mode: 'blacklist'
    #
    Players:
    - 'player1'
    - 'player2'
    - 'player3'
  DisabledWorlds:
    #
    # Choose which worlds the /help command works in.
    #
    # Modes:
    #   blacklist  ->  Worlds listed below will *NOT* have /help functioning (Default Option).
    #   whitelist  ->  Worlds listed below *WILL ONLY* have /help functioning.
    #
    Mode: 'blacklist'
    #
    Worlds:
    - 'Example_World'
    - 'Example_World_the_end'
    - 'Example_World_nether'
  #
  # Settings for the inventory and its items.
  #
  Inventory:
    #
    # The title of the inventory. You can't have more than 32 characters, including color codes.
    # This is also used as the prefix for messages.
    #
    Title: '&7[&aHelp&2GUI&7] '
    #
    # This section allows you to define the shown items, their display name and their lore.
    # Colour codes and placeholders from PlaceholderAPI are supported for both "Name" and "Lore".
    #
    # Placeholders won't be updated/changed, when PlaceholderAPI isn't installed.
    # Exception is the %player% placeholder in "Name" for the Player-item.
    #
    # "Item" uses the 1.13 Item names from Spigot!
    # IDs and the old (1.12 and older) item names aren't supported.
    #
    # Link: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
    #
    Items:
      Info:
        Item: 'BOOK'
        Name: '&7Click on a player head!'
        Lore:
        - ''
        - '&7Click on a playerhead in'
        - '&7the inventory, to send a'
        - '&7help-request to that player!'
        - ''
      NextPage:
        Item: 'SIGN'
        Name: '&bNext page >'
        Lore:
        - ''
      PrevPage:
        Item: 'SIGN'
        Name: '&b< Previous page'
        Lore:
        - ''
      Filler:
        Item: 'BLACK_STAINED_GLASS_PANE'
        Name: '&7'
        Lore:
        - ''
      Player:
        Name: '&7%player%'
        Lore:
        - ''
        - '&7Rank: &b%vault_rank%'
        - '&7Location: &b%player_world%, %player_x%, %player_y%, %player_z%'
        - ''
  #
  # Settings for help requests.
  #
  HelpRequest:
    #
    # The messages for recipient and sender.
    #
    Message:
      #
      # Sender:    The message that is send to the sender of a help request.
      # Recipient: The message that the recipient of a help request recieves.
      #
      # Placeholders:
      #   %sender%     -> Name of the sender of the help request (Only available for Recipient).
      #   %recipient%  -> Name of the recipient of the help request (Only available for Sender).
      #
      #   Placeholders from PlaceholderAPI are supported in both messages.
      #   Those will use values from either the sender or the recipient, depending on where you use them.
      #
      #   Examples:
      #     Sender:    %player_name% -> Name of the sender of the help request.
      #     Recipient: %player_name% -> Name of the recipient of the help request.
      #
      Sender: '&7Help request was sent to &b%recipient%&7!'
      Recipient: '&b%sender% &7needs your help!'
Messages:
  Startup:
    #
    # These messages appear at startup of the plugin
    # Color codes are *NOT* supported here
    #
    # VaultFound:             Will be shown if Vault is found and connected to successfully
    # VaultNotFound:          Will be shown if Vault isn't found
    # PlaceholderAPIFound:    If PlaceholderAPI was found
    # PlaceholderAPINotFound: If PlaceholderAPI wasn't found
    #
    VaultFound: 'Hooked into Vault for group-search'
    VaultNotFound: 'Vault wasn''t found! Group-search disabled.'
    PlaceholderAPIFound: 'Hooked into PlaceholderAPI.'
    PlaceholderAPINotFound: 'Couldn''t find PlaceholderAPI.'
  Errors:
    #
    # Messages for different errors/issues.
    #
    # CommandDisabled:  If the player has the permission helpgui.disablehelp
    # NotOnline:        If the targeted player is offline.
    # DisabledWorld:    Shown when a player uses the command in a disabled world.
    # NoPlayersFound:   If /help [player] had no results.
    # VaultNotEnabled:  If you use /help group:[group] but Vault isn't enabled/installed.
    # NoPermission:     No permission message.
    # NoGroup:          When the player only types "/help group:" without providing a group name.
    # NoUUID:           When the player only types "/help uuid:" without providing a UUID.
    # UnknownError:     Send when a error happens.
    #
    CommandDisabled: '&cYou are not allowed to use this command.'
    NotOnline: '&cThis player is not online!'
    DisabledWorld: '&cYou cannot use HelpGUI in this world.'
    NoPlayersFound: '&cNo players found. :,('
    VaultNotEnabled: '&cVault is not enabled/installed!'
    NoPermission: '&cYou do not have permission for that!'
    NoGroup: '&cYou need to provide a group after &4group:'
    NoUUID: '&cYou need to provide a valid UUID after &4uuid:'
    UnknownError: '&cThere was an unknown error while performing this action!'
  Config:
    #
    # ConfigKey for reloading the config.
    #
    # AttemptReload:       Message on start of reload.
    # Reloaded:            When the plugin successfully reloaded the config.
    # ReloadNotifyPlayer:  Players with helpgui.notify receive this message.
    #
    # Placeholder:
    #   %player% -> Name of the player, that reloaded the plugin. (Only for ReloadNotifyPlayer)
    #
    AttemptReload: '&7Reloading config.yml...'
    Reloaded: '&aconfig.yml successfully reloaded!'
    ReloadNotifyPlayer: '&b%player% &7reloaded the config!'
  UpdateCheck:
    #
    # Messages related to the Update-check of HelpGUI
    # HelpGUI checks for a new version on Server startup and when running /helpgui about
    #
    # Info:       Info shown when running /helpgui about
    # Check:      Shown when HelpGUI checks for a new version.
    # NewVersion: When there is a new version available.
    # UpToDate:   When HelpGUI is up to date.
    # DevVersion: In case when you're running a newer version than available.
    #
    # Placeholders:
    #   %new%     -> The new version available (Only in NewVersion)
    #   %version% -> The current version of HelpGUI (Only in Check and NewVersion)
    #
    Info: '&7This server runs &aHelp&2GUI &7v%version% by Andre_601!'
    Check: '&7Checking version. Please wait...'
    NewVersion: '&6There is a new version of HelpGUI! The new version is &e%new%&6! You run &e%version%&6!'
    UpToDate: '&aHelpGUI is up to date!'
    DevVersion: '&7This version of HelpGUI is newer than the one on Spigot. Is it a dev-version?'
    Errors:
      #
      # Different kinds of error messages for the Update check.
      #
      # NoConnection: When HelpGUI isn't able to connect to the Spiget-API.
      # Unauthorized: When Spiget returns a 401 (Unauthorized) error.
      # InvalidJSON:  When the received JSON from Spiget is invalid/malformed.
      #
      NoConnection: '&cCouldn''t connect to the Spiget-API!'
      Unauthorized: '&cThe Spiget-API returned a 401 error!'
      InvalidJSON: '&cThe received JSON was invalid or malformed.'