#   _   _          _             _____            _   #
#  | | | |        | |           / ____)          (_)  #
#  | |_| |   ___  | |   ____   | /  __   _    _   _   #
#  |_____|  / o \ | |  |  _ \  |_| (__| | |  | | | |  #
#   _   _  |  __/ | |_ | |_) |  ______  | \__/ | | |  #
#  |_| |_|  \___) |__/ |  __/   \____/   \____/  |_|  #
#                      | |                            #
#                      |_|  By Andre_601              #
#                                                     #
# Spigot Resource:                                    #
#   https://www.spigotmc.org/resources/helpgui.33245/ #
#                                                     #
# GitHub:                                             #
#   https://github.com/Andre601/HelpGUI               #
#                                                     #
# Wiki:                                               #
#   https://github.com/Andre601/HelpGUI/wiki          #

Main:
  #
  # Should the banner be visible on startup?
  #
  ShowBanner: true
  DisabledPlayers:
    #
    # Choose which player heads are shown in the GUI
    #
    # Modes:
    #   blacklist  ->  Players listed below will *NOT* be shown in the GUI (Default Option)
    #   whitelist  ->  Players listed below *WILL ONLY* be shown in the GUI
    #   staff      ->  Only players with the "helpgui.staff" permission node will be shown in the GUI
    #
    Mode: 'blacklist'
    #
    Players:
    - player1
    - player2
    - player3
  DisabledWorlds:
    #
    # Choose which worlds the /help command works in
    #
    # Modes:
    #   blacklist  ->  Worlds listed below will *NOT* have /help functioning (Default Option)
    #   whitelist  ->  Worlds listed below *WILL ONLY* have /help functioning
    #
    Mode: 'blacklist'
    #
    Worlds:
    - Example_World
    - Example_World_the_end
    - Example_World_nether
Messages:
  HelpInv:
    #
    # Title:     The title of the inventory
    # NextPage:  Text for the "next page" item
    # PevPage:   Text for the "previous page" item
    # Info:      Title of the Book
    # InfoDesc:  Description of the book (lore)
    #
    Title: '&8[&aHelp&2GUI&8] '
    Info: '&7Click a playerhead!'
    InfoDesc:
    - ''
    - '&7Click on a playerhead in'
    - '&7the inventory, to send a'
    - '&7help-request to that player!'
    - ''
    NextPage: '&bNext page >'
    PrevPage: '&b< Previous page'
  Startup:
    #
    # These messages appear at startup of the plugin
    # Color codes are *NOT* supported here
    #
    # VaultFound:     Will be shown if Vault is found and connected to successfully
    # VaultNotFound:  Will be shown if Vault isn't found
    #
    VaultFound: '&aFound Vault! Enabled Group-Search option.'
    VaultNotFound: '&cCouldn''t find Vault. The group-search option only works with Vault installed and enabled!'
  HelpRequest:
    #
    # Messages for help send/recieved
    #
    # Sender:     Message sent to the sender of the request
    # Recipient:  Message sent to the recipient of the request
    #
    # Placeholders:
    #   %sender%     ->  Name of the sender. (Only in Recipient available!)
    #   %recipient%  ->  Name of the recipient. (Only in Sender available!)
    #
    Sender: '&7Help-Request sent to &b%recipient%&7!'
    Recipient: '&b%sender% &7needs your help!'
  Errors:
    #
    # Messages for different issues.
    #
    # CommandDisabled:  If the player has the permission helpgui.disablehelp
    # NotOnline:        If the targeted player is offline
    # DisabledWorld:    Shown when a player uses the command in a disabled world
    # NoPlayersFound:   If /help [player] had no results
    # VaultNotEnabled:  If you use /help group:[group] but Vault isn't enabled/installed
    #
    CommandDisabled: '&cYou are not allowed to use this command.'
    NotOnline: '&cThis player is not online!'
    DisabledWorld: '&cYou cannot use HelpGUI in this world.'
    NoPlayersFound: '&cNo players found. :,('
    VaultNotEnabled: '&cVault is not enabled/installed!'
    NoPermission: '&cYou do not have permission for that!'
  Config:
    #
    # Messages for reloading the config.
    #
    # AttemptReload:       Message on start of reload.
    # Reloaded:            When the plugin successfully reloaded the config.
    # ReloadNotifyPlayer:  Players with helpgui.notify receive this message.
    #
    # Placeholder:
    #   %player%  ->  Name of the player, that reloaded the plugin.
    #
    AttemptReload: '&7Reloading config.yml...'
    Reloaded: '&aconfig.yml successfully reloaded!'
    ReloadNotifyPlayer: '&b%player% &7reloaded the config!'
