#   _   _          _             _____            _   #
#  | | | |        | |           / ____)          (_)  #
#  | |_| |   ___  | |   ____   | /  __   _    _   _   #
#  |_____|  / o \ | |  |  _ \  |_| (__| | |  | | | |  #
#   _   _  |  __/ | |_ | |_) |  ______  | \__/ | | |  #
#  |_| |_|  \___) |__/ |  __/   \____/   \____/  |_|  #
#                      | |                            #
#                      |_|  By Andre_601              #
#                                                     #
# Spigot Resource:                                    #
#   https://www.spigotmc.org/resources/helpgui.33245/ #
#                                                     #
# GitHub:                                             #
#   https://github.com/Andre601/HelpGUI               #
#                                                     #
# Wiki:                                               #
#   https://github.com/Andre601/HelpGUI/wiki          #

Main:
  DisabledPlayers:
    #
    # Choose which player heads are shown in the GUI
    #
    # Modes:
    #   blacklist  ->  Players listed below will *NOT* be shown in the GUI (Default Option)
    #   whitelist  ->  Players listed below *WILL ONLY* be shown in the GUI
    #   staff      ->  Only players with the "helpgui.staff" permission node will be shown in the GUI
    #
    Mode: 'blacklist'
    #
    Players:
    - player1
    - player2
    - player3
  DisabledWorlds:
    #
    # Choose which worlds the /help command works in
    #
    # Modes:
    #   blacklist  ->  Worlds listed below will *NOT* have /help functioning (Default Option)
    #   whitelist  ->  Worlds listed below *WILL ONLY* have /help functioning
    #
    Mode: 'blacklist'
    #
    Worlds:
    - Example_World
    - Example_World_the_end
    - Example_World_nether
Messages:
  HelpInv:
    #
    # Title:     The title of the inventory
    # NextPage:  Text for the "next page" item
    # PevPage:   Text for the "previous page" item
    # Info:      Title of the Book
    # InfoDesc:  Description of the book (lore)
    #
    Title: '&8[&aHelp&2GUI&8] '
    Info: '&7Click a playerhead!'
    InfoDesc:
    - ''
    - '&7Click on a playerhead in'
    - '&7the inventory, to send a'
    - '&7help-request to that player!'
    - ''
    NextPage: '&bNext page >'
    PrevPage: '&b< Previous page'
  SearchInv:
    #
    # Title:         The title of the inventory
    # PlayersFound:  Displayname of the Item (Book)
    #
    # Placeholders:
    #   %count%  ->  Will be replaced with the amount of players found
    #
    Title: '&8[&aPlayer&2Search&8]'
    PlayersFound: '&aFound &2%count% &aplayers!'
  Startup:
    #
    # These messages appear at startup of the plugin
    # Color codes are *NOT* supported here
    #
    # PluginLoaded:   Will be shown if the plugin is successfully enabled
    # VaultFound:     Will be shown if Vault is found and connected to successfully
    # VaultNotFound:  Will be shown if Vault isn't found
    #
    PluginLoaded: 'HelpGUI successfully enabled!'
    VaultFound: 'Found Vault! Enabled Group-Search option.'
    VaultNotFound: 'Couldn''t find Vault. The group-search option only works with Vault installed and enabled!'
  Console:
    #
    # Console Messages
    # Color codes are NOT supported here!
    #
    # NoPlayer: Will be shown if a command is run in the console
    #
    NoPlayer: 'This command is only for players!'
  HelpRequest:
    #
    # Messages for help send/recieved
    #
    # Sender:     Message sent to the sender of the request
    # Recipient:  Message sent to the recipient of the request
    #
    # Placeholders:
    #   %player%  ->  Sender:    Name of the recipient.
    #                 Recipient: Name of the sender.
    #
    Sender: '&7Help-Request sent to &b%player%&7!'
    Recipient: '&b%player% &7 needs your help!'
  Errors:
    #
    # Messages for different issues.
    #
    # CommandDisabled:  If the player has the permission helpgui.disablehelp
    # NotOnline:        If the targeted player is offline
    # DisabledWorld:    Shown when a player uses the command in a disabled world
    # NoPlayersFound:   If /help [player] had no results
    # NoGroup:          If you didn't give a group after "group:"
    # VaultNotEnabled:  If you use /help group:[group] but Vault isn't enabled/installed
    #
    CommandDisabled: '&cYou are not allowed to use this command.'
    NotOnline: '&cThis player is not online!'
    DisabledWorld: '&cYou cannot use HelpGUI in this world.'
    NoPlayersFound: '&cNo players found. :,('
    NoGroup: '&cPlease add a groupname after group:'
    VaultNotEnabled: '&cVault is not enabled/installed!'
  Commands:
    #
    # FewArgs:             If no argument is given after /hgui
    # UnknownArg:          If an invalid argument is used
    # NoPerm:              No permission message
    # CommandDescription:  Description of /helgui help
    #
    # Placeholders (only in CommandDescription):
    #   %CommandHelp%    ->  /hgui help
    #   %CommandReload%  ->  /hgui reload
    #
    # Hint: '' makes a blank line
    #
    FewArgs: '&7Too few arguments. Type &b/hgui help &7for commands.'
    UnknownArg: '&7Unknown argument. Type &b/hgui help &7for commands.'
    NoPerm: '&cSry. No Permission for that!'
    CommandDescription:
    - '&m----------{&a Help&2GUI'
    - '&b%CommandHelp%'
    - '&7Shows all /hgui commands'
    - ''
    - '&b%CommandReload%'
    - '&7Reloads the files.'
