#   _   _          _             _____            _   #
#  | | | |        | |           / ____)          (_)  #
#  | |_| |   ___  | |   ____   | /  __   _    _   _   #
#  |_____|  / o \ | |  |  _ \  |_| (__| | |  | | | |  #
#   _   _  |  __/ | |_ | |_) |  ______  | \__/ | | |  #
#  |_| |_|  \___) |__/ |  __/   \____/   \____/  |_|  #
#                      | |                            #
#                      |_|  By Andre_601              #
#                                                     #
# Spigot-Link:                                        #
#   https://www.spigotmc.org/resources/helpgui.33245/ #
#                                                     #
# GitHub:                                             #
#   https://github.com/Andre601/HelpGUI               #
#                                                     #
# Wiki:                                               #
#   https://github.com/Andre601/HelpGUI/wiki          #

Main:
  DisabledPlayers:
    #
    # Changes how players are displayed in the GUI
    #
    # Modes:
    #   blacklist  ->  NOT showing players in the GUI, that are set in "DisabledPlayers"
    #   whitelist  ->  ONLY show players in the GUI, that are set in "DisabledPlayers"
    #   staff      ->  Only show players in the GUI, that have the permission "helpgui.staff"
    #
    # HelpGUI will use blacklist as default mode, if a invalid mode was set.
    #
    Mode: 'blacklist'
    #
    # Set players here, that should or should not be shown in the GUI
    # This depends on what you've set in "Mode"
    #
    Players:
    - player1
    - player2
    - player3
  DisabledWorlds:
    #
    # Changes, how HelpGUI handles the command in the different worlds
    #
    # Modes:
    #   blacklist  ->  DISABLE the command /help for all worlds set in "Worlds"
    #   whitelist  ->  ENABLE the command /help ONLY in the worlds set in "Worlds"
    #
    # HelpGUI will use blacklist as default mode, if a invalid mode was set.
    #
    Mode: 'blacklist'
    #
    # Set worlds here, in which /help should or should not work.
    # This depends on what you've set in "Mode"
    #
    Worlds:
    - Example_World
    - Example_World_the_end
    - Example_World_nether
Messages:
  HelpInv:
    #
    # Title:     The title of the inventory
    # NextPage:  Text for the "next page" item
    # PevPage:   Text for the "previous page" item
    # Info:      Title of the Book
    # InfoDesc:  Description of the book (lore)
    #
    Title: '&8[&aHelp&2GUI&8] '
    Info: '&7Click a playerhead!'
    InfoDesc:
    - ''
    - '&7Click on a playerhead in'
    - '&7the inventory, to send a'
    - '&7help-request to that player!'
    - ''
    NextPage: '&bNext page >'
    PrevPage: '&b< Previous page'
  SearchInv:
    #
    # Title:         The title of the inventory
    # PlayersFound:  Displayname of the Item (Book)
    #
    # Placeholders:
    #   %count%  ->  Will be replaced with the amount of players found
    #
    Title: '&8[&aPlayer&2Search&8]'
    PlayersFound: '&aFound &2%count% &aplayers!'
  Startup:
    #
    # These messages appear at startup of the plugin.
    # Colorcodes are NOT supported here!
    #
    # PluginLoaded:   Will be shown, if the plugin was successfully enabled.
    # VaultFound:     If Vault is installed and the plugin successfully connected.
    # VaultNotFound:  Opposite of "VaultFound".
    #
    PluginLoaded: 'HelpGUI successfully enabled!'
    VaultFound: 'Found Vault! Enabled Group-Search option.'
    VaultNotFound: 'Couldn''t find Vault. The group-search option only works with vault installed and enabled!'
  Console:
    #
    # Console-messages.
    # Colorcodes are NOT supported here!
    #
    # NoPlayer:  If you run /help in the console
    #
    NoPlayer: 'The command is only for players!'
  HelpRequest:
    #
    # Messages for help send/recieved
    #
    # Sender:     Message for the sender of the help-request.
    # Recipient:  Message for the recipient of the help-request.
    #
    # Placeholders:
    #   %player%  ->  Sender:    Name of the recipient.
    #                 Recipient: Name of the sender.
    #
    Sender: '&7Help-Request send to &b%player%&7!'
    Recipient: '&b%player% &7 needs your help!'
  Errors:
    #
    # Messages for different issues.
    #
    # CommandDisabled:  If the player has the permission helpgui.disablehelp
    # NotOnline:        If the player is not online.
    # DisabledWorld:    Shown, when a player uses the command in a world, that is in "DisabledWorlds"
    # NoPlayersFound:   If /help [player] had no results.
    # NoGroup:          If you didn't give a group after "group:"
    # VaultNotEnabled:  If you use /help group:[group] but Vault isn't enabled/installed.
    #
    CommandDisabled: '&cYou are not allowed to use this command'
    NotOnline: '&cThis player is not online!'
    DisabledWorld: '&cYou cannot use HelpGUI in this world.'
    NoPlayersFound: '&cNo players found. :,('
    NoGroup: '&cPlease add a groupname after group:'
    VaultNotEnabled: '&cVault is not enabled/installed!'
  Commands:
    #
    # FewArgs:             If no arg is given after /helpgui
    # UnknownArg:          If a invalid arg is used
    # NoPerm:              No permission message
    # CommandDescription:  Description of /helgui help
    #
    # Placeholders (only in CommandDescription):
    #   %CommandHelp%    ->  /hgui help
    #   %CommandReload%  ->  /hgui reload
    #
    # Hint: Use a single space, to make a empty line
    #
    FewArgs: '&7To few arguments. Type &b/hgui help &7for commands.'
    UnknownArg: '&7Unknown argument. Type &b/hgui help &7for commands.'
    NoPerm: '&cSry. No Permission for that!'
    CommandDescription:
    - '&m----------{&a Help&2GUI'
    - '&b%CommandHelp%'
    - '&7Shows all /hgui commands'
    - ''
    - '&b%CommandReload%'
    - '&7Reloads the files.'