#   _   _          _             _____            _   #
#  | | | |        | |           / ____)          (_)  #
#  | |_| |   ___  | |   ____   | /  __   _    _   _   #
#  |_____|  / o \ | |  |  _ \  |_| (__| | |  | | | |  #
#   _   _  |  __/ | |_ | |_) |  ______  | \__/ | | |  #
#  |_| |_|  \___) |__/ |  __/   \____/   \____/  |_|  #
#                      | |                            #
#                      |_|  By Andre_601              #
#                                                     #
# Spigot Resource:                                    #
#   https://www.spigotmc.org/resources/33245/         #
#                                                     #
# GitHub:                                             #
#   https://github.com/Andre601/HelpGUI               #
#                                                     #
# Wiki:                                               #
#   https://github.com/Andre601/HelpGUI/wiki          #

Settings:
  #
  # Debug:      Enable/Disable debug mode. This will print stacktraces and other information prefixed with "[DEBUG]"
  # ShowBanner: Should the banner be shown in console, when the plugin gets enabled?
  #
  Debug: false
  ShowBanner: true
  DisabledPlayers:
    #
    # Choose which player heads are shown in the GUI.
    #
    # You can define one of three modes available (Listed below).
    #
    # The list (Players:) supports player names and UUIDs.
    # You need to prefix UUIDs with uuid: (Case sensitive)
    #
    # For example:
    # - 'uuid:286f8d0c-b571-4720-b7ab-f2929cb38120' # This is the UUID of the player Andre_601
    #
    # Modes:
    #   blacklist  ->  Players listed below will *NOT* be shown in the GUI (Default Option).
    #   whitelist  ->  Players listed below *WILL ONLY* be shown in the GUI.
    #   staff      ->  Only players with the "helpgui.staff" permission node will be shown in the GUI.
    #
    Mode: 'blacklist'
    #
    Players:
    - 'player1'
    - 'player2'
    - 'player3'
  DisabledWorlds:
    #
    # Choose which worlds the /help command works in.
    #
    # Modes:
    #   blacklist  ->  Worlds listed below will *NOT* have /help functioning (Default Option).
    #   whitelist  ->  Worlds listed below *WILL ONLY* have /help functioning.
    #
    Mode: 'blacklist'
    #
    Worlds:
    - 'Example_World'
    - 'Example_World_the_end'
    - 'Example_World_nether'
  #
  #
  #
  Inventory:
    #
    # The title of the inventory. You can't have more than 32 characters, including color codes.
    # This is also used as the prefix for messages.
    #
    Title: '&7[&aHelp&2GUI&7] '
    #
    # This section allows you to define the shown items, their display name and their lore.
    # Colour codes and placeholders from PlaceholderAPI are supported for both "Name" and "Lore".
    #
    # Placeholders won't be updated/changed, when PlaceholderAPI isn't installed.
    # Exception is the %player% placeholder in "Name" for the Player-item.
    #
    # "Item" uses the 1.13 Item names from Spigot!
    # IDs and the old (1.12 and older) item names aren't supported.
    #
    # Link: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
    #
    Items:
      Info:
        Item: 'BOOK'
        Name: '&7Click on a player head!'
        Lore:
        - ''
        - '&7Click on a playerhead in'
        - '&7the inventory, to send a'
        - '&7help-request to that player!'
        - ''
      NextPage:
        Item: 'SIGN'
        Name: '&bNext page >'
        Lore:
        - ''
      PrevPage:
        Item: 'SIGN'
        Name: '&b< Previous page'
        Lore:
        - ''
      Filler:
        Item: 'BLACK_STAINED_GLASS_PANE'
        Name: '&7'
        Lore:
        - ''
      Player:
        Name: '&7%player%'
        Lore:
        - ''
        - '&7Rank: &b%vault_rank%'
        - '&7Location: &b%player_world%, %player_x%, %player_y%, %player_z%'
        - ''
Messages:
  Startup:
    #
    # These messages appear at startup of the plugin
    # Color codes are *NOT* supported here
    #
    # VaultFound:             Will be shown if Vault is found and connected to successfully
    # VaultNotFound:          Will be shown if Vault isn't found
    # PlaceholderAPIFound:    If PlaceholderAPI was found
    # PlaceholderAPINotFound: If PlaceholderAPI wasn't found
    #
    VaultFound: 'Hooked into Vault for group-search'
    VaultNotFound: 'Vault wasn''t found! Group-search disabled.'
    PlaceholderAPIFound: 'Hooked into PlaceholderAPI.'
    PlaceholderAPINotFound: 'Couldn''t find PlaceholderAPI.'
  HelpRequest:
    #
    # Messages for help send/recieved
    #
    # Sender:     Message sent to the sender of the request
    # Recipient:  Message sent to the recipient of the request
    #
    # Placeholders:
    #   %sender%     ->  Name of the sender. (Only in Recipient available!)
    #   %recipient%  ->  Name of the recipient. (Only in Sender available!)
    #
    #   You can use placeholders from PlaceholderAPI.
    #   The placeholders will contain values from either the sender, or recipient, depending on which message it is.
    #   Example: %player_name% turns into the name of the Sender in "Sender".
    #
    Sender: '&7Help-Request sent to &b%recipient%&7!'
    Recipient: '&b%sender% &7needs your help!'
  Errors:
    #
    # Messages for different errors/issues.
    #
    # CommandDisabled:  If the player has the permission helpgui.disablehelp
    # NotOnline:        If the targeted player is offline
    # DisabledWorld:    Shown when a player uses the command in a disabled world
    # NoPlayersFound:   If /help [player] had no results
    # VaultNotEnabled:  If you use /help group:[group] but Vault isn't enabled/installed
    # NoPermission:     No permission message
    # NoGroup:          When the player only types "/help group:" without providing a groupname.
    # NoUUID:           When the player only types "/help uuid:" without providing a UUID.
    # UnknownError:     Send when a error happens.
    #
    CommandDisabled: '&cYou are not allowed to use this command.'
    NotOnline: '&cThis player is not online!'
    DisabledWorld: '&cYou cannot use HelpGUI in this world.'
    NoPlayersFound: '&cNo players found. :,('
    VaultNotEnabled: '&cVault is not enabled/installed!'
    NoPermission: '&cYou do not have permission for that!'
    NoGroup: '&cYou need to provide a group after &4group:'
    NoUUID: '&cYou need to provide a valid UUID after &4uuid:'
    UnknownError: '&cThere was an unknown error while performing this action!'
  Config:
    #
    # ConfigKey for reloading the config.
    #
    # AttemptReload:       Message on start of reload.
    # Reloaded:            When the plugin successfully reloaded the config.
    # ReloadNotifyPlayer:  Players with helpgui.notify receive this message.
    #
    # Placeholder:
    #   %player%  ->  Name of the player, that reloaded the plugin. (Only for ReloadNotifyPlayer)
    #
    AttemptReload: '&7Reloading config.yml...'
    Reloaded: '&aconfig.yml successfully reloaded!'
    ReloadNotifyPlayer: '&b%player% &7reloaded the config!'
