name: HelpGUI
version: 2.0.1-BETA
author: Andre_601

main: com.andre601.helpgui.HelpGUI

api-version: 1.13

commands:
  HelpGUI:
    description: Main HelpGUI-command
    usage: <command>
    aliases: [hgui]
    permission: helpgui.admin
  help:
    description: Shows the Help-Inv
    usage: <command>
    aliases: [h]

permissions:
  helpgui.*:
    description: permission for all HelpGUI-commands
    default: op
    children:
      helpgui.help: true
      helpgui.reload: true
      helpgui.staff: true
  helpgui.disablehelp:
    description: Disables /help for a user/group
    default: false
  helpgui.help:
    description: Let you use /hgui help
    default: op
  helpgui.reload:
    description: Let you use /hgui reload
    default: op
  helpgui.staff:
    description: Permission for the Staff-Mode option
    default: op